[package]
name = "p2p"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "~1.29", features = ["full"] }
priority-queue = "1.3.2"
stun = "0.4.4"
uuid = "1.4.1"
chrono = "0.4.26"
